### PR TITLE
Blogs Component 

### PR DESCRIPTION
**Pull request by HanenAljadani**
Design blogs component, and apply responsiveness 

Screen Shot 1445-01-08 at 12 33 25 AM
Screen Shot 1445-01-08 at 12 19 29 AM

### CODE REVIEW

**Review by AASB7 — APPROVED** [review]
Amazing job

**Review by iif9 — COMMENTED** [review]
Good  Code >`</>`

**Comment by Aryam57** [comment]
good

**Comment by iif9** [comment]
<script>alert('test');</script>

**Pull request merged**
